### ISSUE TITLE
请问为什么替换结果无法导出到output文件夹中

### ISSUE THREAD

**Issue by Wang-Xujing** [beneon/word_proc#2]
请问一下，我按照文档说的配置了对应DocxUpdate各个文件的路径参数,但是运行update_template.py时报错
Traceback (most recent call last):
  File "D:/word_proc-master/word_proc-master/update_template.py", line 18, in <module>
    doc.paragraph_update_all()
  File "D:\word_proc-master\word_proc-master\word_template_update.py", line 155, in paragraph_update_all
    for p in self.doc.paragraphs:
AttributeError: 'str' object has no attribute 'paragraphs'
请问这是出了什么问题了呢？

**Comment by beneon** [comment]
如果是这个git原先带的范例数据（tag_dict.yaml）和模板(template_certi.docx)，用update_template.py是没问题的
所以还是需要你把问题描述的再详细一点，具体做了哪些配置和调整

**Comment by Wang-Xujing** [comment]
> 如果是这个git原先带的范例数据（tag_dict.yaml）和模板(template_certi.docx)，用update_template.py是没问题的
> 所以还是需要你把问题描述的再详细一点，具体做了哪些配置和调整

![image](https://user-images.githubusercontent.com/36768680/129824320-5db00caf-1aae-4028-8c35-37d2f263b6cd.png)

和原文件对比后发现是这里我多改了，这里不需要更改的，问题已解决，感谢
